### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by karlie-tr** [kashish1928/dsci-310-group-02#41]
### Conflict of interest

- [x] As the reviewer I confirm that I have no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [MDS code of conduct](https://ubc-mds.github.io/resources_pages/code_of_conduct/).

### General checks

- [x] **Repository:** Is the source code for this data analysis available? Is the repository well organized and easy to navigate?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?

### Documentation

- [x] **Installation instructions:** Is there a clearly stated list of dependencies? 
- [x] **Example usage:** Do the authors include examples of how to use the software to reproduce the data analysis?
- [x] **Functionality documentation:** Is the core functionality of the data analysis software documented to a satisfactory level?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Code quality
- [x] **Readability:** Are scripts, functions, objects, etc., well named? Is it relatively easy to understand the code?
- [x] **Style guidelides:** Does the code adhere to well known language style guides?
- [ ] **Modularity:** Is the code suitably abstracted into scripts and functions?
- [ ] **Tests:** Are there automated tests or manual steps described so that the function of the software can be verified? Are they of sufficient quality to ensure software robsutness?

### Reproducibility
 
- [x] **Data:** Is the raw data archived somewhere? Is it accessible?
- [x] **Computational methods:** Is all the source code required for the data analysis available?
- [ ] **Conditions:** Is there a record of the necessary conditions (software dependencies) needed to reproduce the analysis? Does there exist an easy way to obtain the computational environment needed to reproduce the analysis?
- [ ] **Automation:** Can someone other than the authors easily reproduce the entire data analysis?

### Analysis report

- [x] **Authors:** Does the report include a list of authors with their affiliations?
- [x] **What is the question:** Do the authors clearly state the research question being asked?
- [x] **Importance:** Do the authors clearly state the importance for this research question?
- [x] **Background**: Do the authors provide sufficient background information so that readers can understand the report?
- [x] **Methods:** Do the authors clearly describe and justify the methodology used in the data analysis? Do the authors communicate any assumptions or limitations of their methodologies?
- [ ] **Results:** Do the authors clearly communicate their findings through writing, tables and figures?
- [x] **Conclusions:** Are the conclusions presented by the authors correct? 
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?
- [x] **Writing quality:** Is the writing of good quality, concise, engaging? 

### Review Comments: 
Overall, the final report is great. The repositorry are well-organized, scripts adhere to `tidyverse` writing style and the report is clear and concise. However, here are some of my suggestions for improving the project:

**1. Functions & Tests**
-  the scripts written to generate the analysis in the `makefile` should use the abstracted functions from milestone 2 (which would be in our package for the final milestone)
- helper data for the tests should use tractable data that differs from the data that we are using to generate the report; for example, we can use the built-in datasets such as `iris` or `mtcars` for `data_sum` since these dataset are easily accessible.
- to test the generated plot, we can use `expect_doppelganger` from the [`vdiffr` package](https://vdiffr.r-lib.org)
- can add some tests for different inputs for each function; for example, what is expected if `data_sum` have an input that is not a dataframe or the column does not exist?

**2. Figures and Tables**
- should include more descriptions for some plots and tables to highlight its relevance to the model building as well as explanation for the generated results
       -  _Figure 3.2:_ highlight some variables that have a high correlation coefficient and those that have low correlation coefficient; 
       - _correlation matrix in 3.9:_ explain what the results in the correlation matrix means
- Typo in `quality` column in cleaned data _Table 2.2_: `Avergae` instead of `Average`; this could be due to a typo in `data_cleaning.R`

**3. Running docker image**
- An error occured when running the docker image using the instructions from README.md:
    ```
    Unable to find image 'dsci-310-group-02:latest' locally
    
    docker: Error response from daemon: pull access denied for dsci-310-group-02, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
    ```
  This might have been due to the username that the repositories of the docker image is not specified.

- was not able to run `make all` or `make -B all` in Docker container

#### Attribution

This was derived from the [JOSE review checklist](https://openjournals.readthedocs.io/en/jose/review_checklist.html) and the ROpenSci review checklist.

**Comment by erichy23** [comment]
To-do
3. Running docker image
- [ ] #45
